---
- name: install basic packages
  yum:
    update_cache: yes
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - tree
    - vim
    - htop
    - mlocate
  tags: [ 'packages' ]

- name: upgrade all packages, including kernel
  yum:
    name: '*'
    state: latest
